package employee.management.system;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;

public class login extends JFrame implements ActionListener {
    JTextField tusername;// we need to declare this globally used to create textfields
    JPasswordField tpassword;
    JButton login,back;


    // The ActionListener interface in Java is part of the Swing framework and is used to handle events generated by
    // GUI components like buttons, menus, and text fields. It provides a way to respond to user interactions with these components
    // by defining the actionPerformed() method that gets invoked when an action event occurs. It is notified against ActionEvent.
    // The ActionListener interface belongs to java.awt.event package. It has actionPerformed() method only.



    login(){

        // Jlable use to make any text visible on Jframe
        JLabel username = new JLabel("Username");
        username.setBounds(40,20,100,30);
        add(username);

        tusername = new JTextField();
        tusername.setBounds(150,20,150,30);
        add(tusername);

        JLabel password = new JLabel("Password");
        password .setBounds(40,70,150,30);
        add(password);

        tpassword = new JPasswordField();
        tpassword.setBounds(150,70,150,30);
        add(tpassword);

        login = new JButton("LOGIN");
        login.setBounds(150,140,150,30);
        login.setBackground(Color.black);
        login.setForeground(Color.white);// to set letters color
        login.addActionListener(this);
        add(login);



        back = new JButton("BACK");
        back.setBounds(150,180,150,30);
        back.setBackground(Color.black);
        back.setForeground(Color.white);// to set letters color
        back.addActionListener(this); // this is used to know the button is clicked or not
        add(back);

        ImageIcon i11 = new ImageIcon(ClassLoader.getSystemResource("icons/second.jpg"));
        Image i22 = i11.getImage().getScaledInstance(600,400,Image.SCALE_DEFAULT);
        ImageIcon i33 = new ImageIcon(i22);
        JLabel imgg = new JLabel(i33);
        imgg.setBounds(350,0,600,400);
        add(imgg);

        ImageIcon i1 = new ImageIcon(ClassLoader.getSystemResource("icons/LoginB.jpg"));
        Image i2 = i1.getImage().getScaledInstance(600,300,Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel img = new JLabel(i3);
        img.setBounds(0,0,600,300);
        add(img);



        setSize(600, 300);
        setLocation(450, 200);
        setLayout(null);
        setVisible(true);

    }

    @Override// This is overriding the actionlistener interface
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == login){
            try{

                String username = tusername.getText();
                String password = tpassword.getText();

                conn conn = new conn();
                String Query = "select * from login where username = '"+ username +"' and passowrd = '"+password+"'";
                ResultSet resultSet = conn.statement.executeQuery(Query);
                if(resultSet.next()){
                    setVisible(false);
                    new Main_class();
                }else{
                    JOptionPane.showConfirmDialog(null, "Invalid Password or Username");
                }

            }catch (Exception E){
                E.printStackTrace();
            }

        } else if (e.getSource() == back){
            {
                System.exit(91);
            }
        }
    }

    public static void main(String[]args){
        login l = new login();
    }
}
